# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e3fdf3867d83034dd0439898a92a6be706ecf823656daf22535f16c5ad9607c4b19e572bec1d3c6d669ddb3aacb57a3f2a591ba92d6b43b11e5f1c40e5edb49

test:
  secret_key_base: 84a3f9b7e4a1d24ef53ec5d540be0b9890f5215045254cf01d89c26f4e37f66d68db1f48e72c3f34ee545e028c09723b44315f480d6bf421f7457d70027db3f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
